// ============================================================
// DISA WORKFORCE ANALYTICS — DAX MEASURES
// v3 - Updated for new dashboard build
// ============================================================


// ============================================================
// STEP 1: CALCULATED COLUMN (Add to Fact_PersonnelActions)
// ============================================================

Voluntary_Flag = 
VAR NOA = Fact_PersonnelActions[NOA Code]
RETURN
    NOA = "302" ||           // Retirement - Voluntary
    LEFT(NOA, 2) = "31" ||   // All 31x codes (Resignation, etc.)
    NOA = "352"              // Voluntary Early Retirement


// ============================================================
// STEP 2: DYNAMIC TITLE
// ============================================================

Dynamic Title = 
VAR StartDt = MIN(Dim_Date[SnapshotDate])
VAR EndDt = MAX(Dim_Date[SnapshotDate])
VAR OrgFilter = IF(
    ISFILTERED(Dim_Organization[Org]),
    SELECTEDVALUE(Dim_Organization[Org], "Multiple Orgs"),
    "All Organizations"
)
RETURN
"DISA Workforce Analytics: " & 
FORMAT(StartDt, "DD MMM YYYY") & " to " & 
FORMAT(EndDt, "DD MMM YYYY") & 
" | " & OrgFilter


// ============================================================
// STEP 3: VOLUNTARY / NON-VOLUNTARY MEASURES
// ============================================================

Voluntary Losses = 
CALCULATE(
    [Total Losses], 
    Fact_PersonnelActions[Voluntary_Flag] = TRUE
)

Non-Voluntary Losses = 
CALCULATE(
    [Total Losses], 
    Fact_PersonnelActions[Voluntary_Flag] = FALSE
)

Voluntary Attrition Rate = 
DIVIDE([Voluntary Losses], [Average On-Hand Count], 0) * 100

Non-Voluntary Attrition Rate = 
DIVIDE([Non-Voluntary Losses], [Average On-Hand Count], 0) * 100

Voluntary Percentage = 
DIVIDE([Voluntary Losses], [Total Losses], 0) * 100

Non-Voluntary Percentage = 
DIVIDE([Non-Voluntary Losses], [Total Losses], 0) * 100


// ============================================================
// STEP 4: NET WORKFORCE CHANGE
// ============================================================

Net Workforce Change = 
[On-Hand Count (End)] - [On-Hand Count (Start)]

Net Change Display = 
VAR Change = [Net Workforce Change]
RETURN
IF(Change >= 0, 
    "+" & FORMAT(Change, "#,##0"),
    FORMAT(Change, "#,##0")
)

Net Change Color = 
IF([Net Workforce Change] >= 0, "#22C55E", "#EF4444")


// ============================================================
// STEP 5: TARGET COMPARISONS
// ============================================================

Attrition Target = 15

Attrition vs Target = 
[Attrition Rate] - [Attrition Target]

Attrition Status = 
SWITCH(
    TRUE(),
    [Attrition Rate] <= 10, "Excellent",
    [Attrition Rate] <= 15, "On Track",
    [Attrition Rate] <= 20, "Warning",
    "Critical"
)

Retention Target = 85

Retention vs Target = 
[Retention Rate] - [Retention Target]

Retention Status = 
IF([Retention Rate] >= [Retention Target], "On Track", "Below Target")


// ============================================================
// STEP 6: INTERNAL / EXTERNAL MOVEMENT
// ============================================================

External Losses = 
CALCULATE(
    COUNTROWS(Fact_PersonnelActions),
    (
        Fact_PersonnelActions[NOA Code] IN {"302","312","317","330","352","355","357","385"} ||
        LEFT(Fact_PersonnelActions[NOA Code], 1) = "3" ||
        Fact_PersonnelActions[NOA Code] = "T352" ||
        Fact_PersonnelActions[NOA Code] = "CAO"
    ),
    Fact_PersonnelActions[Compare Columns] = "DIFFERENT"
)

Internal Moves = 
CALCULATE(
    COUNTROWS(Fact_PersonnelActions),
    Fact_PersonnelActions[NOA Code] IN {"501", "570", "702", "721"},
    Fact_PersonnelActions[Compare Columns] = "DIFFERENT"
)

External Percentage = 
DIVIDE([External Losses], [Total Losses], 0) * 100

Internal Percentage = 
DIVIDE([Internal Moves], [Total Losses], 0) * 100

// Movement Type Breakdown
Promotions = 
CALCULATE(
    COUNTROWS(Fact_PersonnelActions),
    Fact_PersonnelActions[NOA Code] = "702",
    Fact_PersonnelActions[Compare Columns] = "DIFFERENT"
)

Reassignments = 
CALCULATE(
    COUNTROWS(Fact_PersonnelActions),
    Fact_PersonnelActions[NOA Code] = "721",
    Fact_PersonnelActions[Compare Columns] = "DIFFERENT"
)


// ============================================================
// STEP 7: NEW HIRE MEASURES
// ============================================================

New Hire Count = 
VAR EndDate = MAX(Dim_Date[SnapshotDate])
RETURN
CALCULATE(
    COUNTROWS(Fact_EmployeeSnapshot),
    Fact_EmployeeSnapshot[SnapshotDate] = EndDate,
    Fact_EmployeeSnapshot[Tenure Years] < 2,
    Fact_EmployeeSnapshot[IsStudentIntern] = FALSE
)

New Hire Losses = 
CALCULATE(
    [Total Losses],
    Fact_PersonnelActions[Tenure at Departure] < 2
)

First Year Attrition Rate = 
VAR FirstYearLosses = CALCULATE(
    [Total Losses],
    Fact_PersonnelActions[Tenure at Departure] < 1
)
VAR NewHirePool = CALCULATE(
    [On-Hand Count (Start)],
    Fact_EmployeeSnapshot[Tenure Years] < 2
)
RETURN 
DIVIDE(FirstYearLosses, NewHirePool, 0) * 100

New Hire Survival Rate = 
100 - [First Year Attrition Rate]

New Hire Attrition Rate = 
DIVIDE([New Hire Losses], [New Hire Count], 0) * 100


// ============================================================
// STEP 8: VARIANCE MEASURES (for conditional formatting)
// ============================================================

Attrition Variance = 
VAR CurrentOrg = [Attrition Rate]
VAR Overall = CALCULATE([Attrition Rate], REMOVEFILTERS(Dim_Organization))
RETURN CurrentOrg - Overall

Retention Variance = 
VAR CurrentOrg = [Retention Rate]
VAR Overall = CALCULATE([Retention Rate], REMOVEFILTERS(Dim_Organization))
RETURN CurrentOrg - Overall

// Flag for conditional formatting
Above Target Flag = 
IF([Attrition Rate] > [Attrition Target], 1, 0)

Below Retention Target Flag = 
IF([Retention Rate] < [Retention Target], 1, 0)


// ============================================================
// STEP 9: DISPLAY FORMATTING MEASURES
// ============================================================

Attrition Rate Display = 
FORMAT([Attrition Rate], "0.0") & "%"

Retention Rate Display = 
FORMAT([Retention Rate], "0.0") & "%"

Total Losses Display = 
FORMAT([Total Losses], "#,##0")

On-Hand Display = 
FORMAT([On-Hand Count (End)], "#,##0")


// ============================================================
// STEP 10: SPARKLINE SUPPORT (for KPI cards)
// ============================================================

// Use these with small multiples or the Sparkline visual

Attrition Rate Monthly = 
CALCULATE(
    [Attrition Rate],
    ALLEXCEPT(Dim_Date, Dim_Date[YearMonth])
)


// ============================================================
// OPTIONAL: SURVIVAL CURVE MEASURES
// ============================================================

// These require a cohort approach - may need adjustment for your model

Survival 90 Days = 
VAR Cohort = [New Hire Count]
VAR Lost90 = CALCULATE(
    [New Hire Losses],
    Fact_PersonnelActions[Tenure at Departure] < 0.25  // ~90 days
)
RETURN DIVIDE(Cohort - Lost90, Cohort, 0) * 100

Survival 180 Days = 
VAR Cohort = [New Hire Count]
VAR Lost180 = CALCULATE(
    [New Hire Losses],
    Fact_PersonnelActions[Tenure at Departure] < 0.5  // ~180 days
)
RETURN DIVIDE(Cohort - Lost180, Cohort, 0) * 100

Survival 1 Year = 
VAR Cohort = [New Hire Count]
VAR Lost1Yr = CALCULATE(
    [New Hire Losses],
    Fact_PersonnelActions[Tenure at Departure] < 1
)
RETURN DIVIDE(Cohort - Lost1Yr, Cohort, 0) * 100

Survival 2 Years = 
VAR Cohort = [New Hire Count]
VAR Lost2Yr = CALCULATE(
    [New Hire Losses],
    Fact_PersonnelActions[Tenure at Departure] < 2
)
RETURN DIVIDE(Cohort - Lost2Yr, Cohort, 0) * 100
