/// Organizational hierarchy lookup table containing center and directorate codes.
table Dim_Organization
	lineageTag: e3f60163-62f7-421c-9292-5d9da58d959e

	column Dcode
		dataType: string
		isHidden
		lineageTag: 04c38bd9-ee5a-4c55-bc4b-b5b88032cea9
		summarizeBy: none
		sourceColumn: Dcode

		annotation SummarizationSetBy = Automatic

	column Center
		dataType: string
		lineageTag: 0fcf6097-97ca-491d-a260-52495698694f
		summarizeBy: none
		sourceColumn: Center

		annotation SummarizationSetBy = Automatic

	column Org
		dataType: string
		lineageTag: fcfe162c-e5a8-4058-a9cf-5121b51c8592
		summarizeBy: none
		sourceColumn: Org

		annotation SummarizationSetBy = Automatic

	column 'CAM ID'
		dataType: string
		lineageTag: cad5f524-d7d9-49e9-8a84-7f21d8d1238d
		summarizeBy: none
		sourceColumn: CAM ID

		annotation SummarizationSetBy = Automatic

	/// Organizational drill-down from Center to specific Org
	hierarchy 'Organization Hierarchy'

		level Center
			column: Center

		level Organization
			column: Org

	partition Dim_Organization = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://dod365.sharepoint-mil.us/teams/DISA-AttritionRetentionAutomation/Shared%20Documents/Attrition-Retention%20Automation/TEST/OrgMAPPING.xlsx"), null, true),
				    Mapping_Sheet = Source{[Item="Mapping",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Mapping_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Dcode", type text}, {"Center", type text}, {"Org", type text}, {"CAM ID", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

