/// SF-50 personnel action records tracking employee movements, separations, and status changes. Used for attrition and mobility analysis.
table Fact_PersonnelActions
	lineageTag: 3b66b7bd-9e1f-42b5-b9ad-4363b382ea42

	/// Effective date of the personnel action
	column EFFECTIVE_DATE_4
		dataType: dateTime
		formatString: Long Date
		displayFolder: Dates
		lineageTag: 5d78d7f3-8b51-4f6c-b3c1-0f4cb0f4b1de
		summarizeBy: none
		sourceColumn: EFFECTIVE_DATE_4

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Nature of Action code from SF-50 Block 5A - identifies the type of personnel action (e.g., 301=Transfer, 352=Reassignment, 385=Promotion)
	column FIRST_NOA_CODE_5A
		dataType: string
		displayFolder: Action Codes
		lineageTag: d419cb53-7a50-412f-9ca9-1ba717c61b93
		summarizeBy: none
		sourceColumn: FIRST_NOA_CODE_5A

		annotation SummarizationSetBy = Automatic

	/// Description of the first Nature of Action code
	column FIRST_NOA_DESC_5B
		dataType: string
		displayFolder: Action Codes
		lineageTag: 5445c296-e4df-47fc-9ee6-4935c0000bd3
		summarizeBy: none
		sourceColumn: FIRST_NOA_DESC_5B

		annotation SummarizationSetBy = Automatic

	/// Secondary Nature of Action code from SF-50 Block 6A, used when two actions occur simultaneously
	column SECOND_NOA_CODE_6A
		dataType: string
		displayFolder: Action Codes
		lineageTag: 5cc03802-418c-4a3e-8c6c-ef9c142e5d7e
		summarizeBy: none
		sourceColumn: SECOND_NOA_CODE_6A

		annotation SummarizationSetBy = Automatic

	column SECOND_NOA_DESC_6B
		dataType: string
		displayFolder: Action Codes
		lineageTag: 46892f1a-2a59-4d60-b659-41f86f13fbfb
		summarizeBy: none
		sourceColumn: SECOND_NOA_DESC_6B

		annotation SummarizationSetBy = Automatic

	column SF50_APPROVAL_DATE_49
		dataType: string
		displayFolder: Dates
		lineageTag: 67965978-21ca-49e7-8bad-4e2246be6326
		summarizeBy: none
		sourceColumn: SF50_APPROVAL_DATE_49

		annotation SummarizationSetBy = Automatic

	column FROM_POSITION_ORG_LINE1_14
		dataType: string
		lineageTag: 21f8a305-e817-4ae7-9eb8-3adf3b67bd61
		summarizeBy: none
		sourceColumn: FROM_POSITION_ORG_LINE1_14

		annotation SummarizationSetBy = Automatic

	column FROM_POSITION_ORG_LINE2_14
		dataType: string
		lineageTag: bc521991-71c2-4385-8f99-14084b9a833b
		summarizeBy: none
		sourceColumn: FROM_POSITION_ORG_LINE2_14

		annotation SummarizationSetBy = Automatic

	column FROM_POSITION_ORG_LINE3_14
		dataType: string
		lineageTag: 7e3d6056-6731-4bd4-b347-fd2231a516d2
		summarizeBy: none
		sourceColumn: FROM_POSITION_ORG_LINE3_14

		annotation SummarizationSetBy = Automatic

	column FROM_POSITION_ORG_LINE4_14
		dataType: string
		lineageTag: 64f65ec6-ecd9-47c6-9a88-bc4efe773909
		summarizeBy: none
		sourceColumn: FROM_POSITION_ORG_LINE4_14

		annotation SummarizationSetBy = Automatic

	column FROM_POSITION_ORG_LINE5_14
		dataType: string
		lineageTag: f8cd125e-5146-4493-83c2-afb8eab702e3
		summarizeBy: none
		sourceColumn: FROM_POSITION_ORG_LINE5_14

		annotation SummarizationSetBy = Automatic

	column FROM_POSITION_ORG_LINE6_14
		dataType: string
		lineageTag: 916c40c5-2cb4-4865-a601-3438b839c637
		summarizeBy: none
		sourceColumn: FROM_POSITION_ORG_LINE6_14

		annotation SummarizationSetBy = Automatic

	column TO_POSITION_ORG_LINE1_22
		dataType: string
		lineageTag: 8ffddf2e-0c76-4d06-8c89-dfda2c11ec01
		summarizeBy: none
		sourceColumn: TO_POSITION_ORG_LINE1_22

		annotation SummarizationSetBy = Automatic

	column TO_POSITION_ORG_LINE2_22
		dataType: string
		lineageTag: 3b575ee7-d11f-4de3-84da-44d46c7de2fb
		summarizeBy: none
		sourceColumn: TO_POSITION_ORG_LINE2_22

		annotation SummarizationSetBy = Automatic

	column TO_POSITION_ORG_LINE3_22
		dataType: string
		lineageTag: ee5bbffc-71ff-4dc7-86bb-0b98014b5a66
		summarizeBy: none
		sourceColumn: TO_POSITION_ORG_LINE3_22

		annotation SummarizationSetBy = Automatic

	column TO_POSITION_ORG_LINE4_22
		dataType: string
		lineageTag: 7ffcb956-20a8-40ab-86f0-6688ca58f679
		summarizeBy: none
		sourceColumn: TO_POSITION_ORG_LINE4_22

		annotation SummarizationSetBy = Automatic

	column TO_POSITION_ORG_LINE5_22
		dataType: string
		lineageTag: 98f65825-cea0-4698-be99-35548b180c03
		summarizeBy: none
		sourceColumn: TO_POSITION_ORG_LINE5_22

		annotation SummarizationSetBy = Automatic

	column TO_POSITION_ORG_LINE6_22
		dataType: string
		lineageTag: 0c5c432a-cfb8-43f5-9162-9e5f1e0675fc
		summarizeBy: none
		sourceColumn: TO_POSITION_ORG_LINE6_22

		annotation SummarizationSetBy = Automatic

	column DUTY_STATION_DESC_39
		dataType: string
		lineageTag: 1bad2bd7-22f9-441f-8726-1476671049cc
		summarizeBy: none
		sourceColumn: DUTY_STATION_DESC_39

		annotation SummarizationSetBy = Automatic

	column NAME_PERS_1
		dataType: string
		lineageTag: 600000fb-5aef-4e6e-8e10-05edf7f1e142
		summarizeBy: none
		sourceColumn: NAME_PERS_1

		annotation SummarizationSetBy = Automatic

	column FROM_PAY_PLAN_8
		dataType: string
		displayFolder: From Position
		lineageTag: 56ce0586-4f28-4312-a3c7-6e3c1f110b91
		summarizeBy: none
		sourceColumn: FROM_PAY_PLAN_8

		annotation SummarizationSetBy = Automatic

	column FROM_OCC_CODE_9
		dataType: string
		isHidden
		displayFolder: Keys
		lineageTag: f19e78e8-0067-418d-a498-7ab3f140b2a5
		summarizeBy: none
		sourceColumn: FROM_OCC_CODE_9

		annotation SummarizationSetBy = Automatic

	column FROM_GRADE_OR_LEVEL_10
		dataType: string
		displayFolder: From Position
		lineageTag: f2acd369-972f-4bee-a91d-1e985b192518
		summarizeBy: none
		sourceColumn: FROM_GRADE_OR_LEVEL_10

		annotation SummarizationSetBy = Automatic

	column FROM_STEP_OR_RATE_11
		dataType: string
		displayFolder: From Position
		lineageTag: 51684435-86a3-4ffa-908f-9e21a7319c19
		summarizeBy: none
		sourceColumn: FROM_STEP_OR_RATE_11

		annotation SummarizationSetBy = Automatic

	column FROM_BASIC_PAY_12A
		dataType: string
		lineageTag: 39c2d440-353f-4e97-8c34-d03f801be15f
		summarizeBy: none
		sourceColumn: FROM_BASIC_PAY_12A

		annotation SummarizationSetBy = Automatic

	column FROM_ADJ_BASIC_PAY_12C
		dataType: string
		lineageTag: 8bdf5d15-127f-4069-98f1-26ea3db7ccad
		summarizeBy: none
		sourceColumn: FROM_ADJ_BASIC_PAY_12C

		annotation SummarizationSetBy = Automatic

	column FROM_OTHER_PAY_AMOUNT_12D
		dataType: string
		lineageTag: 2ae8f3d4-fb38-4d44-9298-39eaa196c945
		summarizeBy: none
		sourceColumn: FROM_OTHER_PAY_AMOUNT_12D

		annotation SummarizationSetBy = Automatic

	column FROM_PAY_BASIS_13
		dataType: string
		lineageTag: 025939a5-4f8f-4e27-bdb3-bbbcb6440df4
		summarizeBy: none
		sourceColumn: FROM_PAY_BASIS_13

		annotation SummarizationSetBy = Automatic

	column TO_PAY_PLAN_16
		dataType: string
		displayFolder: To Position
		lineageTag: 9862a7d3-041f-48d2-8ccf-db75526e32c0
		summarizeBy: none
		sourceColumn: TO_PAY_PLAN_16

		annotation SummarizationSetBy = Automatic

	column TO_OCC_CODE_17
		dataType: string
		lineageTag: 596ea8f5-a22a-495d-ae4e-c0f068de0197
		summarizeBy: none
		sourceColumn: TO_OCC_CODE_17

		annotation SummarizationSetBy = Automatic

	column TO_GRADE_OR_LEVEL_18
		dataType: string
		displayFolder: To Position
		lineageTag: b92d1d18-921a-433e-8e10-07d435821e94
		summarizeBy: none
		sourceColumn: TO_GRADE_OR_LEVEL_18

		annotation SummarizationSetBy = Automatic

	column TO_STEP_OR_RATE_19
		dataType: string
		lineageTag: b8c2f7b3-f723-4d19-a9d1-d5062d543d0a
		summarizeBy: none
		sourceColumn: TO_STEP_OR_RATE_19

		annotation SummarizationSetBy = Automatic

	column TO_OTHER_PAY_AMOUNT_20D
		dataType: string
		lineageTag: 4c786d55-8a2d-443d-9d04-76fd02fa8135
		summarizeBy: none
		sourceColumn: TO_OTHER_PAY_AMOUNT_20D

		annotation SummarizationSetBy = Automatic

	column TO_PAY_BASIS_21
		dataType: string
		lineageTag: 7fa5c4a1-b440-44fa-b639-4d7a7df7f52e
		summarizeBy: none
		sourceColumn: TO_PAY_BASIS_21

		annotation SummarizationSetBy = Automatic

	column REQUEST_NUMBER
		dataType: string
		lineageTag: b1e4f6ec-05d2-44b1-92ab-b1a6f5b17ad2
		summarizeBy: none
		sourceColumn: REQUEST_NUMBER

		annotation SummarizationSetBy = Automatic

	column FIRST_ACTION_LA_CODE1_5C
		dataType: string
		lineageTag: 3843c3c8-a100-47ac-bbde-aa03676b9c44
		summarizeBy: none
		sourceColumn: FIRST_ACTION_LA_CODE1_5C

		annotation SummarizationSetBy = Automatic

	column FIRST_ACTION_LA_DESC1_5D
		dataType: string
		lineageTag: c48ba738-a0a9-4e7f-bae2-5d89de96c68f
		summarizeBy: none
		sourceColumn: FIRST_ACTION_LA_DESC1_5D

		annotation SummarizationSetBy = Automatic

	column FIRST_ACTION_LA_CODE2_5E
		dataType: string
		lineageTag: 247fe8bf-4d8f-4320-a87d-1485f6dc372f
		summarizeBy: none
		sourceColumn: FIRST_ACTION_LA_CODE2_5E

		annotation SummarizationSetBy = Automatic

	column FIRST_ACTION_LA_DESC2_5F
		dataType: string
		lineageTag: b67f496e-b49e-4a98-8fa4-65d11a596d4a
		summarizeBy: none
		sourceColumn: FIRST_ACTION_LA_DESC2_5F

		annotation SummarizationSetBy = Automatic

	column MOST_RECENT_EMPL_SERIES
		dataType: string
		lineageTag: 9c6245a3-9c0a-4fab-bab9-573d8a29fc02
		summarizeBy: none
		sourceColumn: MOST_RECENT_EMPL_SERIES

		annotation SummarizationSetBy = Automatic

	column MOST_RECENT_EMPL_POSN_TITLE
		dataType: string
		lineageTag: 42b2dccf-40e4-41af-9971-7d6ddb783acf
		summarizeBy: none
		sourceColumn: MOST_RECENT_EMPL_POSN_TITLE

		annotation SummarizationSetBy = Automatic

	column MOST_RECENT_EMPL_MANPOWER_PCN
		dataType: string
		lineageTag: f10c5a95-d972-4311-879e-8171baddcb0c
		summarizeBy: none
		sourceColumn: MOST_RECENT_EMPL_MANPOWER_PCN

		annotation SummarizationSetBy = Automatic

	column EOD
		dataType: string
		displayFolder: Dates
		lineageTag: 1a7afc2f-aa37-4a0e-8cbf-c997fe74ece9
		summarizeBy: none
		sourceColumn: EOD

		annotation SummarizationSetBy = Automatic

	column DT_ARR_SVCG_CCPO
		dataType: dateTime
		formatString: Long Date
		displayFolder: Dates
		lineageTag: a296e7f5-fbde-40b2-b6e5-a382cf077b89
		summarizeBy: none
		sourceColumn: DT_ARR_SVCG_CCPO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'From ORG 2 Digit'
		dataType: string
		isHidden
		displayFolder: Keys
		lineageTag: 0eabffbc-968a-4824-b85f-e4912fd57e02
		summarizeBy: none
		sourceColumn: From ORG 2 Digit

		annotation SummarizationSetBy = Automatic

	column 'To ORG 2 Digit'
		dataType: string
		lineageTag: a5f338ab-0c5e-4de5-81b4-c4a4791b8b3d
		summarizeBy: none
		sourceColumn: To ORG 2 Digit

		annotation SummarizationSetBy = Automatic

	column 'From Org'
		dataType: string
		displayFolder: From Position
		lineageTag: fa4a94a7-e583-469c-a270-5ab6dc81dc6e
		summarizeBy: none
		sourceColumn: From Org

		annotation SummarizationSetBy = Automatic

	column 'To Org'
		dataType: string
		displayFolder: To Position
		lineageTag: 27ac2b83-0d2a-438b-82cc-e1c8e4fc9b26
		summarizeBy: none
		sourceColumn: To Org

		annotation SummarizationSetBy = Automatic

	column 'Compare From and To Organization'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Flags
		lineageTag: 40b7a63c-424b-4756-9171-5610af5321e9
		summarizeBy: none
		sourceColumn: Compare From and To Organization

		annotation SummarizationSetBy = Automatic

	column 'Compare Job Series Changes'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Flags
		lineageTag: 1bed4d92-17bb-4d1d-a9db-a706b56c6e47
		summarizeBy: none
		sourceColumn: Compare Job Series Changes

		annotation SummarizationSetBy = Automatic

	/// Categorizes the separation as Voluntary (resignation, retirement) or Non-Voluntary (termination, RIF)
	column 'Departure Reason'
		dataType: string
		displayFolder: Action Codes
		lineageTag: 86f4f8dd-efd8-4f0c-b06f-9541b09dd09a
		summarizeBy: none
		sourceColumn: Departure Reason

		annotation SummarizationSetBy = Automatic

	/// Identifies if the action represents an Internal move (within org) or External departure (left agency)
	column 'Internal/External Movement'
		dataType: string
		displayFolder: Action Codes
		lineageTag: 818c5738-7a2f-460d-a3ba-9bddc32b4c96
		summarizeBy: none
		sourceColumn: Internal/External Movement

		annotation SummarizationSetBy = Automatic

	/// Indicates if the employee is a student or intern - typically excluded from attrition calculations
	column IsStudentIntern
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Flags
		lineageTag: 7c7b9870-bb2b-4d56-a7bf-3b2161d26968
		summarizeBy: none
		sourceColumn: IsStudentIntern

		annotation SummarizationSetBy = Automatic

	column IsNewHire
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Flags
		lineageTag: accd56ce-ad4a-44d3-a2a8-e97832c4fb7c
		summarizeBy: none
		sourceColumn: IsNewHire

		annotation SummarizationSetBy = Automatic

	column 'Attrition Type'
		dataType: string
		displayFolder: Action Codes
		lineageTag: c876f341-d060-4a3b-98d9-7169e9cb27e1
		summarizeBy: none
		sourceColumn: Attrition Type

		annotation SummarizationSetBy = Automatic

	column 'Internal Path' = ```
			
			IF(
			    Fact_PersonnelActions[Internal/External Movement] = "Internal" && NOT(ISBLANK(Fact_PersonnelActions[From Org])) && NOT(ISBLANK(Fact_PersonnelActions[To Org])),
			    Fact_PersonnelActions[From Org] & " -> " & Fact_PersonnelActions[To Org],
			    BLANK()
			)
			
			```
		lineageTag: 3ddba069-d71a-4470-8b22-28a7b5e34023
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'External Path' = ```
			
			IF(
			    'Fact_PersonnelActions'[Internal/External Movement] = "External" && Fact_PersonnelActions[From Center] <> Fact_PersonnelActions[To Center] && Fact_PersonnelActions[Compare From and To Organization] = FALSE(),
			    'Fact_PersonnelActions'[From Center] & " -> " & 'Fact_PersonnelActions'[Destination Agency]
			)
			
			```
		lineageTag: 8c40fb4a-323d-4081-959d-e95ad1673cf7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CompositeKey
		dataType: string
		isHidden
		displayFolder: Keys
		lineageTag: ddf97e62-f45f-4796-959d-af24f574ba9d
		summarizeBy: none
		sourceColumn: CompositeKey

		annotation SummarizationSetBy = Automatic

	column 'Destination Agency'
		dataType: string
		lineageTag: df2a8168-c94f-4d75-adcf-c9337dae2230
		summarizeBy: none
		sourceColumn: Destination Agency

		annotation SummarizationSetBy = Automatic

	column 'NOA Dec' = Fact_PersonnelActions[FIRST_NOA_CODE_5A] & "-" & Fact_PersonnelActions[FIRST_NOA_DESC_5B]
		lineageTag: 78d88e97-091b-4742-aae0-4a8161124419
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'From Center' = ```
			
			LOOKUPVALUE(
			    'Dim_Organization'[Center],
			    'Dim_Organization'[Dcode],
			    'Fact_PersonnelActions'[From ORG 2 Digit]
			)
			
			```
		displayFolder: From Position
		lineageTag: a795e03b-a3b0-4589-9f08-73649649a343
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'To Center' = ```
			
			LOOKUPVALUE(
			    'Dim_Organization'[Center],
			    'Dim_Organization'[Dcode],
			    'Fact_PersonnelActions'[To ORG 2 Digit]
			)
			
			```
		displayFolder: To Position
		lineageTag: 570ad245-589a-4a55-80da-c22cd62f4a64
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Fact_PersonnelActions = m
		mode: import
		source =
				let
				    SharePointSiteUrl = "https://dod365.sharepoint-mil.us/teams/DISA-AttritionRetentionAutomation",
				    FolderPath = "/Attrition-Retention Automation/TEST/NewTest/",
				    Source = SharePoint.Files(SharePointSiteUrl, [ApiVersion=15]),
				    FolderRows = Table.SelectRows(Source, each Text.StartsWith([Folder Path], SharePointSiteUrl & "/Shared Documents" & FolderPath)),
				    ActionFiles = Table.SelectRows(FolderRows, each Text.Contains([Name], "Actions") and ([Extension] = ".xlsx" or [Extension] = ".xls") and [Attributes]?[Hidden]? <> true),
				    AddData = Table.AddColumn(ActionFiles, "Data", each let FileContent = try Excel.Workbook([Content], null, true){[Item="Table1",Kind="Table"]}[Data] otherwise null in FileContent),
				    RemovedErrors = Table.SelectRows(AddData, each [Data] <> null),
				    Combined = Table.Combine(RemovedErrors[Data]),
				    #"Removed Duplicates" = Table.Distinct(Combined, {"NAME_PERS_1", "FIRST_NOA_CODE_5A", "EFFECTIVE_DATE_4"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"EFFECTIVE_DATE_4", type date}, {"DT_ARR_SVCG_CCPO", type date}, {"FIRST_NOA_CODE_5A", type text}, {"FIRST_NOA_DESC_5B", type text}, {"FIRST_ACTION_LA_CODE2_5E", type text}, {"FROM_POSITION_ORG_LINE6_14", type text}, {"TO_POSITION_ORG_LINE6_22", type text}, {"FROM_OCC_CODE_9", type text}, {"TO_OCC_CODE_17", type text}, {"MOST_RECENT_EMPL_POSN_TITLE", type text}, {"MOST_RECENT_EMPL_MANPOWER_PCN", type text}}),
				    AddFromOrgPrefix = Table.AddColumn(#"Changed Type", "From ORG 2 Digit", each try Text.Start(Text.Trim(Text.AfterDelimiter([FROM_POSITION_ORG_LINE6_14], "-")), 2) otherwise null, type text),
				    AddToOrgPrefix = Table.AddColumn(AddFromOrgPrefix, "To ORG 2 Digit", each try Text.Start(Text.Trim(Text.AfterDelimiter([TO_POSITION_ORG_LINE6_22], "-")), 2) otherwise null, type text),
				    JoinFromOrg = Table.NestedJoin(AddToOrgPrefix, {"From ORG 2 Digit"}, Dim_Organization, {"Dcode"}, "FromMap", JoinKind.LeftOuter),
				    ExpandFromOrg = Table.ExpandTableColumn(JoinFromOrg, "FromMap", {"Org"}, {"From Org"}),
				    JoinToOrg = Table.NestedJoin(ExpandFromOrg, {"To ORG 2 Digit"}, Dim_Organization, {"Dcode"}, "ToMap", JoinKind.LeftOuter),
				    ExpandToOrg = Table.ExpandTableColumn(JoinToOrg, "ToMap", {"Org"}, {"To Org"}),
				    #"Added Compare From and To Organization" = Table.AddColumn(ExpandToOrg, "Compare From and To Organization", each if ([From Org] = null or [To Org] = null) then false else [From Org] = [To Org], type logical),
				    #"Added Compare Job Series Changes" = Table.AddColumn(#"Added Compare From and To Organization", "Compare Job Series Changes", each if [FROM_OCC_CODE_9] = null or [TO_OCC_CODE_17] = null then false else [FROM_OCC_CODE_9] = [TO_OCC_CODE_17], type logical),
				    #"Added Departure Reason" = Table.AddColumn(#"Added Compare Job Series Changes", "Departure Reason", each if [FIRST_ACTION_LA_CODE2_5E] = "ADR" then "DoD-DRP2" else if [FIRST_ACTION_LA_CODE2_5E] = "RZM" then "DoD-DRP1" else if [FIRST_ACTION_LA_CODE2_5E] = "AZM" then "VERA/VSIP" else [FIRST_NOA_DESC_5B], type text),
				    #"Added Internal/External Movement" = Table.AddColumn(#"Added Departure Reason", "Internal/External Movement", each let noa = [FIRST_NOA_CODE_5A] in if (Text.StartsWith(noa, "3") or noa = "CAO" or noa = "T352") then "External" else if (noa = "501" or noa = "570" or noa = "702" or noa = "721") then "Internal" else "Other", type text),
				    AddStudentInternFlag = Table.AddColumn(#"Added Internal/External Movement", "IsStudentIntern", each let title = Text.Lower(Text.From(try [MOST_RECENT_EMPL_POSN_TITLE] otherwise "")), series = Text.From(try [FROM_OCC_CODE_9] otherwise ""), pcn = Text.Upper(Text.From(try [MOST_RECENT_EMPL_MANPOWER_PCN] otherwise "")) in ((Text.Contains(title, "student") or Text.EndsWith(series, "99")) and not (Text.Contains(pcn, "RG") or Text.Contains(pcn, "VT"))), type logical),
				    AddNewHireFlag = Table.AddColumn(AddStudentInternFlag, "IsNewHire", each if [DT_ARR_SVCG_CCPO] <> null and [EFFECTIVE_DATE_4] <> null then Duration.Days([EFFECTIVE_DATE_4] - [DT_ARR_SVCG_CCPO]) <= 730 else false, type logical),
				    #"Added Attrition Type" = Table.AddColumn(AddNewHireFlag, "Attrition Type", each let noa = [FIRST_NOA_CODE_5A], nonVoluntaryCodes = {"330", "355", "357", "385"}, attritionCodes = {"T352", "501", "570", "702", "721", "CAO"} in if List.Contains(nonVoluntaryCodes, noa) then "Non-voluntary" else if (Text.StartsWith(noa, "3") or List.Contains(attritionCodes, noa)) then "Voluntary" else "Not Applicable", type text),
				    #"Added Composite Key" = Table.AddColumn(
				    #"Added Attrition Type",
				    "CompositeKey",
				    each Text.Upper(Text.Select([MOST_RECENT_EMPL_MANPOWER_PCN], {"A".."Z", "a".."z", "0".."9"})) & "-" & Text.Upper(Text.Select([NAME_PERS_1], {"A".."Z", "a".."z"}))
				),
				    #"Added Custom" = Table.AddColumn(#"Added Composite Key", "Destination Agency", each if Text.Contains([Departure Reason], "Termination-Appt In ") then Text.AfterDelimiter([Departure Reason], "Termination-Appt In ")
				else if Text.Contains([Departure Reason], "Termination-Appointment In ") then Text.AfterDelimiter([Departure Reason], "Termination-Appointment In ")
				else [FIRST_NOA_CODE_5A] & "-" & [FIRST_NOA_DESC_5B]),
				    #"Trimmed Text" = Table.TransformColumns(#"Added Custom",{}),
				    #"Replaced Value" = Table.ReplaceValue(#"Trimmed Text","Department","Dpt",Replacer.ReplaceText,{"Destination Agency"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Central Intelligence Agency","CIA",Replacer.ReplaceText,{"Destination Agency"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","National Aeronautics and Space Administration","NASA",Replacer.ReplaceText,{"Destination Agency"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Dpt of the Air Force","Air Force",Replacer.ReplaceText,{"Destination Agency"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Dpt of the Army","Army",Replacer.ReplaceText,{"Destination Agency"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Dpt of the Navy","Navy",Replacer.ReplaceText,{"Destination Agency"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","-Voluntary","",Replacer.ReplaceText,{"Destination Agency"})
				in
				    #"Replaced Value6"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

